# fly.toml app configuration file generated for test-fly-mattermost-gpt-bot on 2023-08-16T10:39:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-fly-mattermost-gpt-bot"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
